apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: db-ns
  labels:
    app: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: imyourkm/mongodb:test
        ports:
        - containerPort: 27017
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: db-cf
              key: MONGO_DB_PORT
