apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 710281024320.dkr.ecr.ap-northeast-2.amazonaws.com/ingress-kitchen
        ports:
        - containerPort: 3000
