apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend-ns
spec:
  ports:
  - port: 3000
    targetPort: 8000
    nodePort: 30736
  selector:
    app: frontend
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend-ns
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: backend
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: db-ns
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
